### ISSUE TITLE
Transfer to the KYI Organisation

### ISSUE THREAD

**Issue by PlytonRexus** [Know-Your-ISM/kyi-flutter#1]
Hi, @SWIFT1437!
Thanks for your contribution to making KYI accessible from all forms of platforms.
I am making this issue to request the transfer of ownership of this repository to @Know-Your-ISM. The transfer will make it easier for everybody to access your source and also be able to use your binaries.

Thanks,
Mihir

**Comment by PlytonRexus** [comment]
Feel free to ask any questions.

**Comment by SWIFT1437** [comment]
> Feel free to ask any questions.

    Oka
